import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/constants/app_colors.dart';
import '../../core/utils/currency_formatter.dart';
import '../../providers/lead_provider.dart';
import '../../providers/user_provider.dart';
import '../../providers/fee_provider.dart';
import '../widgets/summary_card.dart';

class SalesTeamView extends StatefulWidget {
  const SalesTeamView({super.key});

  @override
  State<SalesTeamView> createState() => _SalesTeamViewState();
}

class _SalesTeamViewState extends State<SalesTeamView> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Provider.of<UserProvider>(context, listen: false).fetchUsers();
    });
  }

  @override
  Widget build(BuildContext context) {
    final userProvider = Provider.of<UserProvider>(context);
    final leadProvider = Provider.of<LeadProvider>(context);
    final feeProvider = Provider.of<FeeProvider>(context);

    final salesExecs = userProvider.users.where((u) => u.role == 'SALES_EXECUTIVE' || u.role == 'SALES_HEAD').toList();

    return Padding(
      padding: const EdgeInsets.all(20),
      child: Column(
        cross: CrossAxisAlignment.start,
        children: [
          const Text('Sales Team Members & Performance Overview', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 4),
          const Text('Monitor sales executives, assigned lead pipelines, closing stats, and revenue generated.', style: TextStyle(fontSize: 12, color: AppColors.textSecondary)),
          const SizedBox(height: 20),

          Expanded(
            child: ListView.builder(
              itemCount: salesExecs.length,
              itemBuilder: (context, idx) {
                final exec = salesExecs[idx];
                final execLeads = leadProvider.rawLeads.where((l) => l.assignedTo == exec.name || l.createdBy == exec.email).toList();
                final convertedLeads = execLeads.where((l) => l.status == 'Converted').toList();
                final conversionRate = execLeads.isNotEmpty ? ((convertedLeads.length / execLeads.length) * 100).toStringAsFixed(1) : '0';

                // Revenue generated by exec's converted students
                final convertedPhoneNumbers = convertedLeads.map((l) => l.phone).toSet();
                final execStudents = feeProvider.students.where((s) => convertedPhoneNumbers.contains(s.phone) || s.convertedByExecutive == exec.email).toList();
                final totalRevenue = execStudents.fold(0.0, (sum, s) => sum + s.paidFee);

                return Card(
                  margin: const EdgeInsets.only(bottom: 16),
                  child: Padding(
                    padding: const EdgeInsets.all(18),
                    child: Column(
                      cross: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            CircleAvatar(
                              radius: 20,
                              backgroundColor: AppColors.primary,
                              child: Text(exec.name.isNotEmpty ? exec.name[0].toUpperCase() : 'S', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                            ),
                            const SizedBox(width: 12),
                            Column(
                              cross: CrossAxisAlignment.start,
                              children: [
                                Text(exec.name, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                                Text('${exec.email} • ${exec.phone}', style: const TextStyle(fontSize: 11, color: AppColors.textSecondary)),
                              ],
                            ),
                            const Spacer(),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                              decoration: BoxDecoration(
                                color: AppColors.success.withOpacity(0.1),
                                borderRadius: BorderRadius.circular(20),
                              ),
                              child: Text(
                                'Revenue Generated: ${CurrencyFormatter.format(totalRevenue)}',
                                style: const TextStyle(color: AppColors.success, fontWeight: FontWeight.bold, fontSize: 12),
                              ),
                            ),
                          ],
                        ),
                        const Divider(height: 24),

                        // Performance Metrics Grid
                        Row(
                          children: [
                            Expanded(child: SummaryCard(title: 'Assigned Leads', value: '${execLeads.length}', icon: Icons.leaderboard, iconColor: AppColors.info)),
                            const SizedBox(width: 12),
                            Expanded(child: SummaryCard(title: 'Deals Closed / Converted', value: '${convertedLeads.length}', icon: Icons.verified_user, iconColor: AppColors.success)),
                            const SizedBox(width: 12),
                            Expanded(child: SummaryCard(title: 'Closing Ratio', value: '$conversionRate%', icon: Icons.pie_chart, iconColor: AppColors.warning)),
                          ],
                        ),
                        const SizedBox(height: 16),

                        // Active Lead Pipeline Table
                        const Text('Active Lead Pipeline', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                        const SizedBox(height: 8),
                        if (execLeads.isEmpty)
                          const Text('No leads assigned to this executive.', style: TextStyle(fontSize: 12, color: AppColors.textMuted, fontStyle: FontStyle.italic))
                        else
                          SingleChildScrollView(
                            scrollDirection: Axis.horizontal,
                            child: DataTable(
                              headingRowHeight: 36,
                              dataRowHeight: 44,
                              columns: const [
                                DataColumn(label: Text('Lead ID')),
                                DataColumn(label: Text('Lead Name')),
                                DataColumn(label: Text('Phone')),
                                DataColumn(label: Text('Course')),
                                DataColumn(label: Text('Next Follow-up')),
                                DataColumn(label: Text('Status')),
                              ],
                              rows: execLeads.take(5).map((l) {
                                return DataRow(
                                  cells: [
                                    DataCell(Text(l.leadId, style: const TextStyle(fontWeight: FontWeight.bold, color: AppColors.primary))),
                                    DataCell(Text(l.name)),
                                    DataCell(Text(l.phone)),
                                    DataCell(Text(l.courseInterested)),
                                    DataCell(Text(l.nextFollowup.isNotEmpty ? l.nextFollowup : '-')),
                                    DataCell(Text(l.status, style: const TextStyle(fontWeight: FontWeight.bold))),
                                  ],
                                );
                              }).toList(),
                            ),
                          ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
